# Generated by Django 5.0.4 on 2024-04-23 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='logo',
        ),
        migrations.AddField(
            model_name='candidato',
            name='aMaterno',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='candidato',
            name='aPaterno',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(default=None, upload_to='fotos'),
        ),
        migrations.AddField(
            model_name='partido',
            name='descripcion',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.candidato', verbose_name='Candidato')),
            ],
        ),
    ]
