# Generated by Django 5.0.4 on 2024-04-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0002_remove_partido_logo_candidato_amaterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
