# Generated by Django 5.0.4 on 2024-04-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0003_alter_partido_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='aMaterno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='aPaterno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(upload_to='fotos'),
        ),
    ]
