# Generated by Django 5.0.4 on 2024-04-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0004_alter_candidato_amaterno_alter_candidato_apaterno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votacion',
            name='fecha_hora',
        ),
    ]
