# Generated by Django 5.0.4 on 2024-04-23 18:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0006_ejemplo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ejemplo',
        ),
        migrations.AddField(
            model_name='votacion',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
